/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.percent;

public final class R {
    public static final class attr {
        public static final int layout_aspectRatio = 0x7f01011d;
        public static final int layout_heightPercent = 0x7f010115;
        public static final int layout_marginBottomPercent = 0x7f01011a;
        public static final int layout_marginEndPercent = 0x7f01011c;
        public static final int layout_marginLeftPercent = 0x7f010117;
        public static final int layout_marginPercent = 0x7f010116;
        public static final int layout_marginRightPercent = 0x7f010119;
        public static final int layout_marginStartPercent = 0x7f01011b;
        public static final int layout_marginTopPercent = 0x7f010118;
        public static final int layout_widthPercent = 0x7f010114;
    }
    public static final class styleable {
        public static final int[] PercentLayout_Layout = { 0x7f010114, 0x7f010115, 0x7f010116, 0x7f010117, 0x7f010118, 0x7f010119, 0x7f01011a, 0x7f01011b, 0x7f01011c, 0x7f01011d };
        public static final int PercentLayout_Layout_layout_aspectRatio = 9;
        public static final int PercentLayout_Layout_layout_heightPercent = 1;
        public static final int PercentLayout_Layout_layout_marginBottomPercent = 6;
        public static final int PercentLayout_Layout_layout_marginEndPercent = 8;
        public static final int PercentLayout_Layout_layout_marginLeftPercent = 3;
        public static final int PercentLayout_Layout_layout_marginPercent = 2;
        public static final int PercentLayout_Layout_layout_marginRightPercent = 5;
        public static final int PercentLayout_Layout_layout_marginStartPercent = 7;
        public static final int PercentLayout_Layout_layout_marginTopPercent = 4;
        public static final int PercentLayout_Layout_layout_widthPercent = 0;
    }
}
